name: Create release

on:
  workflow_dispatch:

jobs:
  build-cms:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_AUTH_TOKEN }}"
          npm ci
          
      - name: Build
        run: npm run production -w @yago/cms
      
      - name: Upload vendor manifest
        uses: actions/upload-artifacts@v3
        with:
          name: vendor-manifest
          path: ./packages/cms/public/vendor-manifest.json

  build:
    runs-on: ubuntu-latest
    needs: build-cms
    
    strategy:
      fail-fast: false
      matrix:
        package: [article]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download vendor manifest
        uses: actions/download-artifact@v3
        with:
          name: vendor-manifest
      
      - name: Test
        run: cat vendor-manifest.json
        
#       - name: Install dependencies
#         run: |
#           npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_AUTH_TOKEN }}"
#           npm ci
        
#       - name: Build
#         run: npm run production -w @yago/${{ matrix.package }}
