name: Create release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        package: [cms, article]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_AUTH_TOKEN }}"
          npm ci
        
      - name: Compile
        run: npm run production -w @yago/${{ matrix.package }}
