name: Create release

on:
  workflow_dispatch:

jobs:
  build-cms:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_AUTH_TOKEN }}"
          npm ci
          
      - name: Build
        run: npm run production -w @yago/cms
      
      - name: Upload vendor manifest
        uses: actions/upload-artifact@v3
        with:
          name: vendor-manifest
          path: ${{ github.workspace }}/packages/cms/public/js/vendor-manifest.json

      - name: Create dist zip
        run: cd public && tar -czvf dist.tar.gz dist
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          repository: yago-cms/cms
          files: public/dist.tar.gz


  build:
    runs-on: ubuntu-latest
    needs: build-cms
    
    strategy:
      fail-fast: false
      matrix:
        package: [article]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download vendor manifest
        uses: actions/download-artifact@v3
        with:
          name: vendor-manifest
      
      - name: Copy vendor manifest
        run: |
          mkdir -p ${{ github.workspace }}/packages/cms/public/js/
          cat vendor-manifest.json > ${{ github.workspace }}/packages/cms/public/js/vendor-manifest.json
        
      - name: Install dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_AUTH_TOKEN }}"
          npm ci
        
      - name: Build
        run: npm run production -w @yago/${{ matrix.package }}
