name: Create release

on:
  push:
    tags:
      - 'v*'

env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build-cms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_AUTH_TOKEN }}"
          npm ci

      - name: Build
        run: npm run production -w @yago/cms

      - name: Upload vendor manifest
        uses: actions/upload-artifact@v3
        with:
          name: vendor-manifest
          path: ${{ github.workspace }}/packages/cms/resources/dist/js/vendor-manifest.json

      - name: Create dist zip
        run: cd ${{ github.workspace }}/packages/cms/resources && tar -czvf dist.tar.gz dist

      - name: Split
        uses: symplify/monorepo-split-github-action@2.1
        with:
            package_directory: packages/cms

            repository_organization: yago-cms
            repository_name: cms

            user_name: "Johan Grönberg"
            user_email: "johan@formsmedjan.se"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          repository: yago-cms/cms
          token: ${{ secrets.ACCESS_TOKEN }}
          files: ${{ github.workspace }}/packages/cms/resources/dist.tar.gz

  build:
    runs-on: ubuntu-latest
    needs: build-cms

    strategy:
      fail-fast: false
      matrix:
        package: [article]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download vendor manifest
        uses: actions/download-artifact@v3
        with:
          name: vendor-manifest

      - name: Copy vendor manifest
        run: |
          mkdir -p ${{ github.workspace }}/packages/cms/resources/dist/js/
          cat vendor-manifest.json > ${{ github.workspace }}/packages/cms/resources/dist/js/vendor-manifest.json

      - name: Install dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_AUTH_TOKEN }}"
          npm ci

      - name: Build
        run: npm run production -w @yago/${{ matrix.package }}

      - name: Create dist zip
        run: cd ${{ github.workspace }}/packages/${{ matrix.package }}/resources && tar -czvf dist.tar.gz dist

      - name: Split
        uses: symplify/monorepo-split-github-action@2.1
        with:
            package_directory: packages/${{ matrix.package }}

            repository_organization: yago-cms
            repository_name: ${{ matrix.package }}

            user_name: "Johan Grönberg"
            user_email: "johan@formsmedjan.se"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          repository: yago-cms/${{ matrix.package }}
          token: ${{ secrets.ACCESS_TOKEN }}
          files: ${{ github.workspace }}/packages/${{ matrix.package }}/resources/dist.tar.gz